# Generated by Django 3.0.8 on 2021-02-23 14:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 23, 14, 15, 55, 565373, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Reminders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminderType', models.IntegerField(verbose_name='Reminder Type')),
                ('name', models.CharField(max_length=250)),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.CharField(max_length=100)),
                ('priority', models.IntegerField(verbose_name='Priority')),
                ('isAttached', models.BooleanField(default='False')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CustomUser')),
            ],
        ),
    ]
